[package]
name = "proxify-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proxify"
path = "src/main.rs"

[dependencies]
proxify-core = { path = "../proxify-core" }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security",
] }
